# Generated by Django 5.0.2 on 2026-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours_Safaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(help_text='Include country code', max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('is_processed', models.BooleanField(default=False, help_text='Mark as True when the inquiry has been responded to', verbose_name='Is Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed Date')),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff', verbose_name='Staff Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser and device information', verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('category', models.CharField(choices=[('safari', 'Safari Packages'), ('trekking', 'Mountain Trekking'), ('booking', 'Booking & Payment'), ('transport', 'Transportation'), ('accommodation', 'Accommodation'), ('general', 'General Questions')], default='general', max_length=20, verbose_name='Category')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Inquiry Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Inquiry Type',
                'verbose_name_plural': 'Inquiry Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscription Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('unsubscribe_token', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='tour',
        ),
        migrations.DeleteModel(
            name='WhyChooseUs',
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['submitted_at'], name='Tours_Safar_submitt_05981f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['is_processed'], name='Tours_Safar_is_proc_111728_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['email'], name='Tours_Safar_email_48cc40_idx'),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
